### ISSUE TITLE
Collection name

### ISSUE THREAD

**Issue by EricMaris** [Donders-Institute/donders-institute.github.io#26]
I read in the collection attribute table that the iRODS collection identifier, specified as [o].[ou].[coll_name], will be fully system-generated. Does this also apply to the [coll_name] part, or can this part be specified by the OU_admin at the time of initiation? The latter would be nice, because this would make the webdav interface more intelligible.

**Comment by hurngchunlee** [comment]
Hi,

It is technically possible, and would be nicer in terms of flexibility.  But I am not in favour of it as it can easily result in issues if the name can be fully specified by OU_admin.  The issues I see are:

 - inconsistent naming convention: for the moment, the `coll_name` is a composition of `type`, `projectId` and 3-digit random number (in order to make it unique).  In this way, we are sure the name is consistent and thus easier for communications with researchers.

- special character issues:  it's always a difficult issue when special character is presented in directory namespace.

Hong

**Comment by EricMaris** [comment]
A proposal:

coll_name = type + projectId + 3-digit random number + 6-letter acronym

The acronym is optional, must be provided by the future collection manager, and cannot contain special characters. The latter is enforced by the CMS that performs character validation for the acronym field.

Eric

**Comment by hurngchunlee** [comment]
What do you mean by "future manager"?

Note that the `coll_name` can only be given at the time of creation.  Therefore, the research admin must provide the acronym to CMS although this can be given by the first manager (is this what you meant by "future manager"?).

**Comment by robertoostenveld** [comment]
I don't think we should do acronyms, but only abstract (mostly numeric) IDs. 

Acronyms works if the number of projects is small, but won't scale (since after a few years all interesting acronyms will be taken and people will start requiring longer acronyms to be supported...).

**Comment by EricMaris** [comment]
Future manager = the user that will become manager when the research admin has assigned him to the collection.

In a sprint demo meeting, we discovered the possibility to copy-paste the full collection name (including its namespace) into one of Cyberduck's  window, allowing for direct access to that collection's files. This reduces the need for an intelligible name.
